### ISSUE TITLE
use credentials to run a command

### ISSUE THREAD

**Issue by mgazzin** [danieljoos/wincred#10]
Hello Daniel,

nice package.
Do you have an example of how to use credentials to run a command?
Kindly let me know.
Thanks.

**Comment by mgazzin** [comment]
> You want to run a system command from your golang application? Should this application receive the credential data? If yes, stuff like environment variables or IPC mechanisms can be used.
Yes, that's what I mean.
In you example "Retrieve credentials" with this line:

```
cred, err := wincred.GetGenericCredential("myGoApplication")
```
I get a cred object.
How may I use his in an exec.Command call?

**Comment by danieljoos** [comment]
You want a string of the credential data?
Just cast it with `string(cred.CredentialBlob)` (see example on `README`)
You might want to write this to stdin of the invoked command or so.
