### ISSUE TITLE
nativeCredEnumerate should follow safe cast pattern

### ISSUE THREAD

**Issue by JohnRusk** [danieljoos/wincred#13]
Currently this routine contains the following code

```
        var filterPtr uintptr
	if !all {
		filterUtf16Ptr, _ := syscall.UTF16PtrFromString(filter)
		filterPtr = uintptr(unsafe.Pointer(filterUtf16Ptr))
	} else {
		filterPtr = 0
	}
	ret, _, err := procCredEnumerate.Call(
		filterPtr,
```

I believe it would be more correct if the cast to the uintptr was moved inside the proc call, as follows:

```
       var filterPtr unsafe.Pointer // change type
	if !all {
		filterUtf16Ptr, _ := syscall.UTF16PtrFromString(filter)
		filterPtr = unsafe.Pointer(filterUtf16Ptr) // remove (delay) the cast
	} else {
		filterPtr = nil    // nil instead of zero
	}
	ret, _, err := procCredEnumerate.Call(
		uintptr(filterPtr),  // do the cast now
```

This is as per the guidelines for the unsafe package, to only cast to uintptr inside the arg list of the sys call. 

Is there any actual danger in the current code?  I'm not 100% sure. I do wonder if filterUtf16Ptr could be garbage collected before the call to procCredEnumerate, in which case the uintPtr would technically be invalid. 

In any case, it would be nice for folks who happen to use automated (or manual) checks on their codebase not to come up against this as an apparent violation of the guidelines.

**Comment by danieljoos** [comment]
Hi,

Thanks for the comment.

Running `go vet` shows me only three possible misuses of `unsafe.Pointer`, but only in the tests. (Haven't found any way to workaround them, but it's test code, so....).

I think the better way would be to store the `filterUtf16Ptr` instead. Casting the `unsafe.Pointer` removes the link for the garbage collector and indeed could cause an issue. Casting it as `uintptr` only converts it to an integer.

So maybe something like this would be safer:

```go
var filterPtr *uint16 = nil
if !all {
    filterPtr, _ = syscall.UTF16PtrFromString(filter)
}
ret, _, err := procCredEnumerate.Call(
    uintptr(unsafe.Pointer(filterPtr)),
    0,
    uintptr(unsafe.Pointer(&count)),
    uintptr(unsafe.Pointer(&pcreds)),
)
```
It would even get rid of the `else`.

**Comment by JohnRusk** [comment]
That looks even cleaner.

**Comment by danieljoos** [comment]
Ok, cool. I'll update it accordingly (probl. today or tomorrow). Will also add a public function to use the filter string.
