### ISSUE TITLE
TestSysCredRead_Mock failed

### ISSUE THREAD

**Issue by asakaxgit** [danieljoos/wincred#14]
TestSysCredRead_Mock failed by panic below.
> --- FAIL: TestSysCredRead_Mock (0.00s)
>     sys_test.go:87: 
>         	Error Trace:	sys_test.go:87
>         	            				sys_test.go:31
>         	            				sys.go:79
>         	            				sys_test.go:95
>         	            				sys_test.go:95
>         	Error:      	Not equal: 
>         	            	expected: 0xc000044500
>         	            	actual  : 0x0
>         	Test:       	TestSysCredRead_Mock
>     sys_test.go:98: 
>         	Error Trace:	sys_test.go:98
>         	Error:      	Expected value not to be nil.
>         	Test:       	TestSysCredRead_Mock
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x8 pc=0x72d75a]

> goroutine 7 [running]:
> testing.tRunner.func1.1(0x78dd40, 0xacf5c0)
> 	V:/bin/go1.14.2/src/testing/testing.go:940 +0x2fc
> testing.tRunner.func1(0xc0001145a0)
> 	V:/bin/go1.14.2/src/testing/testing.go:943 +0x400
> panic(0x78dd40, 0xacf5c0)
> 	V:/bin/go1.14.2/src/runtime/panic.go:969 +0x174
> github.com/danieljoos/wincred.TestSysCredRead_Mock(0xc0001145a0)
> 	c:/workspaces/wincred/sys_test.go:100 +0x70a
> testing.tRunner(0xc0001145a0, 0x80b750)
> 	V:/bin/go1.14.2/src/testing/testing.go:991 +0xe3
> created by testing.(*T).Run
> 	V:/bin/go1.14.2/src/testing/testing.go:1042 +0x35e
> FAIL	github.com/danieljoos/wincred	0.182s

It's weird that "PASS" when I was running that as debug mode then step-over.
I see that your copying strings conversion are correct.

### Environment
Win 10 1909 (build 18363.778)
go version go1.14.2 windows/amd64
Debug mode was ran by Delve via VSCode

**Comment by danieljoos** [comment]
Thanks for posting the issue.
I can reproduce it with go1.14.2 on my machine, too.
Will have a look what's going on there. Could be caused by the misuse of `unsafe.Pointer` that i needed to do for the testing. Maybe it's time to finally address that. I haven't found a better way, without using `cgo`, yet.

**Comment by danieljoos** [comment]
I added some workaround that worked here: ff39ef3defdafd2621d5f6e7a3d5b2bcdca56537

Could you please try if that is working for you, as well?
