### ISSUE TITLE
Lack of support for tokens over 2500 characters

### ISSUE THREAD

**Issue by jeremyjpaws** [danieljoos/wincred#18]
## Issue

There is a lack of support for wincred tokens over 2500 characters.

If more than 2500 characters are used, issues and errors such as "The stub received bad data" may occur when trying to authenticate against a container repository. See the related issues at (1,2,3).

Note that this maybe not quite a wincred bug directly, but a result of a limitation in the underlying Windows API and its credential store; however I am not sure in this.

## References:

1. https://github.com/aws/aws-cli/issues/5636
2. https://github.com/docker/docker-credential-helpers/issues/190
3. https://github.com/Azure/azure-cli/issues/4843

**Comment by danieljoos** [comment]
Hi,

thanks for reporting this issue.
I'll have a look immediately.

Cheers,
Daniel

**Comment by danieljoos** [comment]
Alright, this seems to be a limitation of the Windows API.
The `CRED_MAX_CREDENTIAL_BLOB_SIZE` is `5 * 512 = 2560 Bytes`. I haven't found any way to work around this limit.
I tried to add a credential with more (~5k Bytes) in C++ and it failed with exactly the same error there, too.

**Comment by nick4fake** [comment]
@danieljoos 
-- I haven't found any way to work around this limit.
Possible workaround is using multiple credentials to store it

**Comment by danieljoos** [comment]
A hint has been added to the README. Closing this issue.
