### ISSUE TITLE
GenericCredential and UTF16

### ISSUE THREAD

**Issue by skemper** [danieljoos/wincred#19]
First, thanks for this library, it has been very helpful for the app that I'm working on!

While using it I noticed an inconsistency with `GenericCredential`s.  This isn't a problem with the library, but more of a warning to other developers, so I'm curious if and how we could make people aware.

The Microsoft documentation on the `CREDENTIALW` data structure returned by the `CredReadW` call states that

> Credentials are expected to be portable. Applications should ensure that the data in CredentialBlob is portable. The application defines the byte-endian and alignment of the data in CredentialBlob.

When adding data to the credentials store *solely* through a single application, this works fine, and What You Put In is What You Get Out.  However, credentials can also be managed by the users through Credential Manager in the Control Panel.  If a user modifies the credential through that interface, the application's choices are lost.  In Go's case, a password that was encoded with UTF-8 is replaced by a password encoded with UTF-16LE, for example.  When reading the data after this out-of-band modification, your code can fail in fun and exciting ways.

So maybe a warning of some sort is in order in the README?  Or is this something that Windows developers will know already, so it doesn't need to be documented?  As might be guessed, I am not typically a Windows guy so this might be my own ignorance showing through.  In any case I'd be happy to make a PR if an update is warranted.

**Comment by danieljoos** [comment]
I added a comment plus example to the README.
