### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by ezbercihk** [danieljoos/wincred#55]
When I upgrade to https://github.com/danieljoos/wincred/releases/tag/v1.2.1, my builds are failing with the following message:

```
#14 [cache-builder 5/5] RUN GOARCH=amd64 GOOS=linux go build ./vendor/...
#14 sha256:1285cb2bacc52a653248371160801135b4a2f0310e3f54108e42a10dd214843c
#14 47.94 # github.com/danieljoos/wincred
#14 47.94 vendor/github.com/danieljoos/wincred/wincred.go:21:19: undefined: sysERROR_BAD_USERNAME
#14 ERROR: executor failed running [/bin/sh -c GOARCH=amd64 GOOS=linux go build ./vendor/...]: exit code: 1
```

**Comment by danieljoos** [comment]
This happened on non-Windows platforms.
Should be fixed now.
However, this package only works on Windows. On every other platform (Linux in your case) it will always return an `Operation not supported` error.
