### ISSUE TITLE
web credentials

### ISSUE THREAD

**Issue by winteraz** [danieljoos/wincred#6]
It seems the current API is providing access only to the generic credentials(i.e. windows credentials). This is a feature request to provide access to the web credentials as well.

 Here is how to do that in c#
```using System;
using Windows.Security.Credentials;

class Program {
    static void Main(string[] args) {
        PasswordVault vault = new PasswordVault();
        foreach (var cred in vault.RetrieveAll()) {
            cred.RetrievePassword();
            Console.WriteLine("Resource: {0}", cred.Resource);
            Console.WriteLine("UserName: {0}", cred.UserName);
            Console.WriteLine("Password: {0}", cred.Password);
        }
    }
}```

**Comment by danieljoos** [comment]
The `Windows.Security.Credentials` API seems to be available for .NET only. So it won't be easy to access it from golang.
I'll further look into this and see if it can be accessed from outside the .NET-world.
Are those the credentials visible in the control panel as "Web Credentials"?

**Comment by winteraz** [comment]
Yes, they are visible in the control panel as "Web Credentials"/


Sent from Outlook<http://aka.ms/weboutlook>
________________________________

**Comment by danieljoos** [comment]
There seems to be an undocumented API for the Windows Vault.
I decided to create a new package for accessing it.
Find it here: https://github.com/danieljoos/winvault
Still WIP.
